#If you use a database then uncomment below lines and update db properties accordingly
spring:
  application:
    name: LAU Eud Backend
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:15://localhost/lau-eud
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration
    postgresql.transactional-lock: false
    placeholders:
      LAU_EUD_DB_PASSWORD: laupass

flyway:
  noop:
    strategy: "false"

idam:
  s2s-auth:
    url: ${S2S_URL:http://localhost:4554}
  api:
    url: ${IDAM_API_URL:http://localhost:4554}

rd:
  professional:
    url: ${RD_PROFESSIONAL_API_URL:http://localhost:4554}

dummy-jwt: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsYXVfZXVkX2JhY2tlbmQiLCJleHAiOjE3NjExNDc5MzJ9.yrK05Rc5cl5mXxlHafediHLPq_IM0EwKRjAnY6sp2kwg8xh2hHuxF0xz7F2K5diwwLazy1uVyASHOB7lluO3sA
